apiVersion: v1
kind: Service
metadata:
  name: haufe-service
spec:
  type: NodePort  # Use LoadBalancer for EKS
  selector:
    app: haufe-app
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
